baseURL = "https://musing-archimedes-695310.netlify.app"
disqusShortname = ""
googleAnalytics = ""
paginate = "3"
summaryLength = "15"
theme = "bigspring"
title = "RedWolf"
[markup.goldmark.renderer]
unsafe = true
